/**
 * Runtime accessor for the Amazon template snapshot. The JSON file is
 * generated by scripts/snapshot-amazon-template.ts from Amazon's
 * SUNGLASSES.xlsm and committed to the repo. This module owns the typing
 * + lookup helpers; everything downstream (column mapper, validator, AI
 * prompt) reads through here so they all bind to the same truth.
 *
 * Re-run the CLI when Amazon ships a new template version. The
 * source.version field on the snapshot lets us detect drift if needed.
 */
import snapshotJson from "./template-snapshot.json";

export interface AmazonColumnDef {
  name: string;
  label: string;
  index: number;
  required: boolean;
  group: string | null;
  definition: string | null;
  example: string | null;
  maxLength: number | null;
  enumValues: string[] | null;
}

export interface AmazonTemplateSnapshot {
  source: {
    path: string;
    templateType: string | null;
    version: string | null;
    signature: string | null;
    snapshotTakenAt: string;
  };
  /** Row index where data starts (0-indexed = 3 → Amazon's row 4). */
  dataRowIndex: number;
  columns: AmazonColumnDef[];
}

const snapshot = snapshotJson as AmazonTemplateSnapshot;

// Build O(1) lookup once at module load — the snapshot is immutable.
const byName: Map<string, AmazonColumnDef> = new Map(
  snapshot.columns.map((c) => [c.name, c]),
);

/** All 313 column definitions, in their Template-sheet order. */
export function getAmazonColumns(): readonly AmazonColumnDef[] {
  return snapshot.columns;
}

/** Lookup by internal attribute name (e.g. "item_sku"). */
export function getAmazonColumn(name: string): AmazonColumnDef | undefined {
  return byName.get(name);
}

/** Valid enum values for an attribute, or null when the column is free-text. */
export function getEnumValues(attr: string): readonly string[] | null {
  return byName.get(attr)?.enumValues ?? null;
}

/** Whether a column is required according to Amazon's Data Definitions sheet. */
export function isRequired(attr: string): boolean {
  return byName.get(attr)?.required ?? false;
}

/** Max character length when present; null = no hard cap parsed from docs. */
export function getMaxLength(attr: string): number | null {
  return byName.get(attr)?.maxLength ?? null;
}

/** Where the writer should start populating data rows (Amazon's row 4). */
export function getDataRowIndex(): number {
  return snapshot.dataRowIndex;
}

/** Source metadata — useful for surfacing the template version in the UI. */
export function getSnapshotSource() {
  return snapshot.source;
}

/**
 * Case-sensitivity matters: Amazon validates literal enum strings. We
 * still offer this case-insensitive fallback so a tag like "metal" matches
 * "Metal" — the caller normalises before persisting.
 */
export function findEnumValue(attr: string, candidate: string): string | null {
  const values = getEnumValues(attr);
  if (!values) return null;
  const exact = values.find((v) => v === candidate);
  if (exact) return exact;
  const lower = candidate.trim().toLowerCase();
  return values.find((v) => v.toLowerCase() === lower) ?? null;
}
