/**
 * Build a COGS manual journal payload from a CogsAggregation + shared
 * mappings (cogs/inventory accounts) + a tracking option.
 *
 * Structure: per-SKU pair of Dr COGS / Cr Inventory lines so the journal
 * preserves SKU-level audit detail. Each line description names the SKU
 * and its unit cost, e.g. "JX1001-BLK Monroe (Black) — 12 units @ $2.10"
 * so accountants reading the journal can verify each line independently.
 */

import type { CogsLine, CogsAggregation } from "./cogs-aggregator";
import type { TrackingMapping, XeroJournalLine, XeroManualJournalPayload } from "./journal-builder";

export type CogsAccounts = {
  cogsAccountCode: string;
  cogsAccountName: string | null;
  inventoryAccountCode: string;
  inventoryAccountName: string | null;
};

export type BuildCogsJournalResult =
  | { ok: true; payload: XeroManualJournalPayload; warnings: string[] }
  | { ok: false; error: string };

export function buildCogsJournal(opts: {
  aggregation: CogsAggregation;
  accounts: CogsAccounts;
  tracking: TrackingMapping | null;
  /** Reference back to the parent payout journal — included in the narration. */
  payoutId: number;
  payoutDate: string;
  platform: string;
  status?: "POSTED" | "DRAFT";
}): BuildCogsJournalResult {
  const { aggregation, accounts, tracking, payoutId, payoutDate, platform } = opts;
  const status = opts.status ?? "POSTED";

  if (aggregation.lines.length === 0) {
    return {
      ok: false,
      error: "No COGS lines to post (no orders or all SKUs had qty 0 after refund netting)",
    };
  }
  if (!accounts.cogsAccountCode || !accounts.inventoryAccountCode) {
    return {
      ok: false,
      error: "Shared COGS / Inventory accounts not mapped. Set them under the Shared accounts card.",
    };
  }

  const trackingTag = tracking
    ? [{ TrackingCategoryID: tracking.trackingCategoryId, Option: tracking.trackingOptionName ?? "" }]
    : undefined;

  const lines: XeroJournalLine[] = [];
  for (const line of aggregation.lines) {
    if (line.lineTotal <= 0) continue;
    const description = describeLine(line);

    // Dr COGS — positive LineAmount
    lines.push({
      LineAmount: line.lineTotal,
      AccountCode: accounts.cogsAccountCode,
      Description: description,
      Tracking: trackingTag,
    });
    // Cr Inventory — negative LineAmount
    lines.push({
      LineAmount: -line.lineTotal,
      AccountCode: accounts.inventoryAccountCode,
      Description: description,
      Tracking: trackingTag,
    });
  }

  const sum = lines.reduce((acc, l) => acc + l.LineAmount, 0);
  const warnings: string[] = [...aggregation.warnings];
  if (Math.abs(sum) > 0.01) {
    warnings.push(`COGS journal lines net to ${sum.toFixed(2)} (should be 0).`);
  }

  const narration = buildNarration({
    payoutId,
    payoutDate,
    platform,
    skuCount: aggregation.lines.length,
    totalUnits: aggregation.totalUnits,
    totalCost: aggregation.totalCost,
    warningCount: warnings.length,
  });

  return {
    ok: true,
    payload: {
      Narration: narration,
      Date: payoutDate,
      Status: status,
      JournalLines: lines,
    },
    warnings,
  };
}

function describeLine(line: CogsLine): string {
  const product = line.productName || "";
  const color = line.colorName ? ` (${line.colorName})` : "";
  const unitsLabel = line.quantity === 1 ? "unit" : "units";
  return `${line.sku} ${product}${color} — ${line.quantity} ${unitsLabel} @ $${line.unitCostAtSale.toFixed(2)}`.trim();
}

function buildNarration(opts: {
  payoutId: number;
  payoutDate: string;
  platform: string;
  skuCount: number;
  totalUnits: number;
  totalCost: number;
  warningCount: number;
}): string {
  const parts = [
    `COGS for ${humanPlatform(opts.platform)} payout #${opts.payoutId}`,
    `${opts.payoutDate}`,
    `${opts.totalUnits} unit${opts.totalUnits === 1 ? "" : "s"} across ${opts.skuCount} SKU${opts.skuCount === 1 ? "" : "s"}`,
    `Total COGS $${opts.totalCost.toFixed(2)}`,
  ];
  if (opts.warningCount > 0) parts.push(`(${opts.warningCount} warning${opts.warningCount === 1 ? "" : "s"})`);
  parts.push("Generated by the-frame");
  return parts.join(" | ");
}

function humanPlatform(platform: string): string {
  switch (platform) {
    case "shopify_dtc":       return "Shopify Retail";
    case "shopify_afterpay":  return "Shopify Afterpay";
    case "shopify_wholesale": return "Shopify Wholesale";
    case "faire":             return "Faire";
    case "amazon":            return "Amazon";
    case "tiktok_shop":       return "TikTok Shop";
    default:                  return platform;
  }
}
