/**
 * Apply scripts/data/amazon-listings-v1.2.json to catalog_amazon_listings.
 *
 * The JSON is generated by scripts/generate-amazon-listings-v1.2.ts
 * (hand-authored v1.2 copy + assembler backends — no Claude API call).
 * Products are resolved by sku_prefix so the same file applies to local
 * and prod databases regardless of row ids.
 *
 * Upsert semantics: copy fields (title, bullets, description,
 * generic_keywords) are always overwritten; suggested_* enum columns are
 * PRESERVED on existing rows (they came from the earlier vision runs and
 * the column-mapper needs them).
 *
 * Usage:
 *   npx tsx scripts/import-amazon-listings.ts [--dry-run]
 *
 * Prod (after deploy):
 *   railway ssh --service the-frame "cd /app && npx tsx scripts/import-amazon-listings.ts"
 */
import fs from "fs";
import path from "path";
import { sqlite, db } from "@/lib/db";
import { copyVersions } from "@/modules/catalog/schema";

const PROMPT_VERSION = "amazon-v1.2-2026-06-10";
const MODEL = "claude-opus-4-8-chat"; // authored in-chat, no API call

interface ListingJson {
  sku: string;
  productName: string;
  title: string;
  bullets: [string, string, string, string, string];
  description: string;
  genericKeywords: string;
}

function main() {
  const dryRun = process.argv.includes("--dry-run");
  const jsonPath = path.join(process.cwd(), "scripts", "data", "amazon-listings-v1.2.json");
  const listings = JSON.parse(fs.readFileSync(jsonPath, "utf-8")) as ListingJson[];
  console.log(`${listings.length} listings in ${jsonPath}${dryRun ? " (DRY RUN)" : ""}\n`);

  const now = new Date().toISOString();
  let updated = 0, inserted = 0, missing = 0;

  const upsert = sqlite.prepare(`
    INSERT INTO catalog_amazon_listings (
      id, product_id, amazon_title,
      bullet_point_1, bullet_point_2, bullet_point_3, bullet_point_4, bullet_point_5,
      product_description, generic_keywords,
      model_used, prompt_version, generated_at, created_at, updated_at
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'), datetime('now'))
    ON CONFLICT(product_id) DO UPDATE SET
      amazon_title = excluded.amazon_title,
      bullet_point_1 = excluded.bullet_point_1,
      bullet_point_2 = excluded.bullet_point_2,
      bullet_point_3 = excluded.bullet_point_3,
      bullet_point_4 = excluded.bullet_point_4,
      bullet_point_5 = excluded.bullet_point_5,
      product_description = excluded.product_description,
      generic_keywords = excluded.generic_keywords,
      model_used = excluded.model_used,
      prompt_version = excluded.prompt_version,
      generated_at = excluded.generated_at,
      updated_at = datetime('now')
      -- suggested_* columns intentionally untouched: vision-derived enums
      -- from prior runs stay valid for the column-mapper.
  `);

  for (const l of listings) {
    const p = sqlite.prepare("SELECT id FROM catalog_products WHERE sku_prefix = ?")
      .get(l.sku) as { id: string } | undefined;
    if (!p) { console.error(`  ✗ ${l.sku} ${l.productName}: product not found`); missing++; continue; }

    const existing = sqlite.prepare(
      "SELECT id FROM catalog_amazon_listings WHERE product_id = ?",
    ).get(p.id);

    if (!dryRun) {
      upsert.run(
        crypto.randomUUID(), p.id, l.title,
        l.bullets[0], l.bullets[1], l.bullets[2], l.bullets[3], l.bullets[4],
        l.description, l.genericKeywords,
        MODEL, PROMPT_VERSION, now,
      );
      // Audit trail, same as the AI pipeline's persist().
      db.insert(copyVersions).values({
        productId: p.id,
        fieldName: "amazon_listing",
        content: JSON.stringify({
          title: l.title, bullet_points: l.bullets,
          description: l.description, generic_keywords: l.genericKeywords,
        }),
        aiModel: MODEL,
      }).run();
    }
    existing ? updated++ : inserted++;
    console.log(`  ${existing ? "↻" : "+"} ${l.sku} ${l.productName}`);
  }

  console.log(`\nDone. ${updated} updated, ${inserted} inserted, ${missing} missing${dryRun ? " (no writes — dry run)" : ""}.`);
  if (missing > 0) process.exit(1);
}

main();
